Use bind host address instead of localhost
davidmhewitt/appcenter-website pull request #217
Opened 2023-07-13 02:46 UTC by RMcNeely

## Fix node 18+ support for Frontend

### Background

Solves #123 

The mocks-server dependency does not appear to support IPV6 (as far as I can tell [server.host](https://www.mocks-server.org/docs/configuration/options/#serverhost) documentation specifically mentions IPV4 addresses). You can see this in node 18+ by starting the mocks server and trying to reach `http://[::1]:3100/api/apps/recently_updated` the IPV6 localhost address. Swap the localhost address with something else that mocks-server can resolve. 

### Testing:

Using node 18 or newer start the dev server and make sure that the pages load correctly

2023-07-13 02:47 UTC, RMcNeely commented
See also https://github.com/mock-server/mockserver/issues/1051

2023-07-25 07:54 UTC, davidmhewitt requested changes

2023-07-25 07:54 UTC, davidmhewitt commented on frontend/.env.development
> +NEXT_PUBLIC_API_BASE_URL=http://0.0.0.0:3100
Would it work to use `127.0.0.1` instead of `0.0.0.0` here?

I don't really like this approach because these environment variables are used for forming URLs to do requests to the backend. It's one thing to tell a server to host on `0.0.0.0`, but it's a bit more weird to do a GET request to `http://0.0.0.0/something`. So if `127.0.0.1` works, I'd rather use that.

2023-07-26 18:34 UTC, RMcNeely commented on frontend/.env.development
> +NEXT_PUBLIC_API_BASE_URL=http://0.0.0.0:3100
I think that should be fine. The issue is that localhost resolves to the IPV6 address on newer versions of node so it should be fine explicitly pointing at the IPV4 loop back address. Let me test and push changes.

2023-07-27 07:25 UTC, davidmhewitt approved these changes
Thanks!

2023-07-27 07:25 UTC, merged